server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

  jpa:
    hibernate:
      ddl-auto: update #create or update or none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #변수 명과 DB 칼럼명을 그대로 매핑
    show-sql: true
    
    
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 569127029061-bg2snercc2ogq73ibl037fq2usqnf74q.apps.googleusercontent.com
            client-secret: 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
            scope:
            - email
            - profile
            
          facebook:
            client-id: 7120397421366905
            client-secret: 21a919193efa90cf91fb0989d7aaa968
            scope:
            - email
            - public_profile
            
          naver:
            client-id: iHi3Jy_Ptsg8q2RbZKr0
            client-secret: vORjJfWuQ0
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌.